app = "p-659806"
primary_region = "cdg"

[build]
image = "Dockerfile"

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
